// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMSAMG.Models.PRACTICEDB;

namespace WMSAMG.Migrations
{
    [DbContext(typeof(PRACTICEDBContext))]
    [Migration("20201027092115_practicedb")]
    partial class practicedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WMSAMG.Models.PRACTICEDB.Department", b =>
                {
                    b.Property<int>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Dept_Code")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeptName")
                        .HasColumnName("Dept_Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("DeptCode")
                        .HasName("PK__tmp_ms_x__8985FE74043BF62F");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WMSAMG.Models.PRACTICEDB.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Emp_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeptCode")
                        .HasColumnName("Dept_Code")
                        .HasColumnType("int");

                    b.Property<int?>("EmpAge")
                        .HasColumnName("Emp_Age")
                        .HasColumnType("int");

                    b.Property<string>("EmpCity")
                        .HasColumnName("Emp_City")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("EmpName")
                        .HasColumnName("Emp_Name")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.HasKey("EmpId");

                    b.HasIndex("DeptCode");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WMSAMG.Models.PRACTICEDB.Employee", b =>
                {
                    b.HasOne("WMSAMG.Models.PRACTICEDB.Department", "DeptCodeNavigation")
                        .WithMany("Employee")
                        .HasForeignKey("DeptCode")
                        .HasConstraintName("FK_Employee_ToDepartment");
                });
#pragma warning restore 612, 618
        }
    }
}
